name: first Workflow
on: 
  push :
    branches: ["main"]
  workflow_dispatch: 
  
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello Build
        run: echo build phase done
        
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello test
        run: echo test phase done
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello deploy
        run: echo deploy phase done
  
