name : first Workflow
on : 
  push :
    branches : ["main"]
  workflow_dispatch : 
  
jobs : 
  runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v3
      - name : send mail
      
      
     
      
      
      
